on: push

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: 'script -q -e -c "bash {0}"'
    steps:
      - uses: actions/checkout@v3
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: lcov
          version: 1.0
      - name: Set up CMake and dependencies
        env:
          ENABLE_TESTS: ON
          ENABLE_COVERAGE: ON
          DOWNLOAD_LOCAL_JULIA: ON
        run: cmake -S . -B build
      - name: Build
        run: cmake --build build -t tests -j 4
      - name: Run tests
        run: build/tests
      - name: Generate coverage report
        run: ./generate-coverage-report.sh build
      - name: Upload Coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: build/coverage-report
      - name: Verify 100% line coverage
        run: grep -P "lines\.+:" coverage-meta.txt --color=never | grep "100.0%" -q
