on: push

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: 'script -q -e -c "bash {0}"'
    steps:
      - uses: actions/checkout@v3
      - name: Set up CMake and dependencies
        env:
          ENABLE_TESTS: ON
          ENABLE_COVERAGE: ON
          DOWNLOAD_LOCAL_JULIA: ON
        run: cmake -S . -B build
      - name: Build
        run: cmake --build build -t tests -j 4
      - name: Run tests
        run: build/tests
      - uses: codecov/codecov-action@v3
        with:
          directory: build/CMakeFiles/juliapp.dir
          gcov: true
          gcov_include: src/eval.cpp.gcda
